after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  distributions: sdist bdist_wheel
  on:
    repo: timmartin19/open-source-init
    tags: true
  password:
    secure: B6kF1YjYHbVa+rtySbo4Vh9p2PO2dz3dFou8ue9nirGVJR6nRreSLi9RlNB6sZ5mOqmOPLGO6DOCw5B5ZPVk9qktbyEIQSGN2fd2QPfz1q8X9vuLuSQKEE92syxZ7b55IR/fph7ZQfBUEhYWiJtmcmRrrSOf5QR+4um4e9j9UT/UcO02YQLXSszw/VTiwEy77JMb//fsxPLre7Z3+rTsCD5rHl30D8qqWW8qVW5hLfW+nF+nc9cbuFLn5nxWYQrPbRF5uQcA2WYvaNFadO1sMeW7CbpMA/1M6sgdrh7veEEa8nH9hvzOVboBHUtMmP54A0Qd3DCr7dAZPZ9iEnPdBFsaClt5xuekr/2A95TviTJK6Z3b3lnGCPSoddJy2BChGQWTgsVcYyZ1gA998DDghH226SsP3s3/CoZoAWcm7lK1JYSeWzrLX25RP0SLitCS91vujxxXODCX/e1jWYm4dPJARKaqbssFiGeCn1u9EIZu5v54GO/Z3NAPyMZQgJbHXlt+OLzeVnv84rj+Vxek7qVVgYFQ79STRyUwRNRrLW+dgxv8O1AvqmYpLv3KPO+BJUHOYh7gpcql5NPiD+Cb1g1m+ZQAZJdjrdJ5EDZqqAh5PzcrestH7lrID9jCpmHmA9WW8tyEt2oY+jt29OvHu2Z3ygCAN0PsaUHk0FQETkM=
  provider: pypi
  user: timmartin19
env:
  global:
  - secure: NN2CTMX7qXN5Tgic8nDDoa146tlnS1HAW7JyuItka2WjK60CXakxm0b6F1nN7pJImG8PCo+p8I2xvSimvI4/GdgfT9JoNpwGxG0PFx3daOf1YV9HBSTwa/ePEivwfNEzroDt5U8Q7/4hHYaOKS6LIyhJVzXinsSVNuizptGOT7UhalZW7y5xtN6pGII2mNHslL6Hrro0d9qafzQsBI25UeBaFB7X94bQuYq31RwTH/tc5XXSZbsG/P3Q8o1uHPUWNU1cLr5jD3OkDYOXcjQJ+jjgBfBk6hr5nEd6Lbj+kYjAXprUxTorMS4gK90Mkkn3z7K0VsBI5pz23jTR817DD1ODUI1hfJDYWBTS1SICM4YBXYmBrt5iJb9qWGNY0JpYuw1JC0CgevqnbrdJUI166BXVrUhfYAKWlOK9px5wwgNssSYFKPW+0omqPI17CS2AGbEQXNkKzkoLLwwpH/cHOZtIPE8oO/s+vrqGW3MroqZi0D6XysmQXqFyXJkNjl6eGLuaH4jAE6S7Dghl/01wgbbsyUNGBWo9ULWMn+ZpRI/sKv2qlxQbDjQ290U47Pp/hlR29uzPbobP7McVRWBA9/+rJ1awe9Oo3IDPeb5+2eoauFn49k/+9Ujd+Rcz4wCy20y1RpxaDm2lbLF0hsRXdmnTshxQJWZQguXrRMccFso=
install:
- pip install .
- pip install coverage
language: python
python:
- '3.5'
- '3.4'
script: coverage run -m unittest discover
